spring:
  application:
    name: our-baby
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/our-baby
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver